server:
  port: 9000

spring:
  datasource:
    url: ${DATABASE_URL}  # ?? ?? ??
    username: ${DATABASE_USERNAME}  # ?? ?? ??
    password: ${DATABASE_PASSWORD}  # ?? ?? ??
    driver-class-name: org.postgresql.Driver

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  h2.console.enabled: true

  sql:
    init:
      mode: always

  data:
    rest:
      base-path: /api
      detection-strategy: annotated

  thymeleaf3:
    decoupled-logic: true

logging:
  level:
    com.springboot.board: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

management:
  endpoints:
    web:
      exposure:
        include: "*"

debug: false

jwt:
  secret: ${JWT_SECRET}
